# kubectl api-resources
# kubectl api-versions
# kubectl explain deployment
# kubectl create -f deployment-definition.yml
# kubectl get deployment
# kubectl delete deployment myapp-replicaset
# kubectl replace -f deployment-definition.yml -> if we update the file to bring up the new replicas
# kubectl scale deployment --replicas=3 myapp-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end